name: case_study
channels:
  - plotly
  - theochem
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - notebook
  - pandas
  - plotly
  - python
  - python-dateutil
  - python_abi
  - scipy
  - setuptools
  - yaml
  - wget
  - pip
  - pip:
    - keras
    - keras-applications
    - keras-preprocessing
    - markdown
    - matplotlib
    - networkx
    - numba
    - numpy
    - paramz
    - ply
    - scikit-learn
    - tensorboard
    - tensorflow
    - tensorflow-estimator
    - torch
