name: case_study
channels:
  - plotly
  - theochem
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - notebook
  - pandas
  - python
  - python-dateutil
  - python_abi
  - scipy
  - yaml
  - wget
  - pip
  - pip:
    - keras
    - keras-applications
    - keras-preprocessing
    - markdown
    - matplotlib
    - numpy
    - scikit-learn
    - tensorboard
    - tensorflow
    - tensorflow-estimator
    - torch
